version: '3.8'

x-environment: &base
  NAMESRV_ADDR: "10.10.0.169:9876;10.10.0.169:9877;10.10.0.169:9878"
  JAVA_OPT_EXT: "-server -Xms256m -Xmx1024m -Xmn128m -XX:MetaspaceSize=128m  -XX:MaxMetaspaceSize=320m"


services:
  namesev-0:
    image: apache/rocketmq:5.3.1
    container_name: namesev-0
    privileged: true
    volumes:
      - /home/rocketmq/dledger/logs/node1:/opt/logs/rocketmqlogs
      - /home/rocketmq/dledger/node0/conf/nameserv0.propterties:/home/rocketmq/conf/nameserv.conf
    environment:
      ROCKETMQ_NAMESRV_PORT: 9876
      JAVA_OPT_EXT: "-Duser.home=/opt -Xms256m -Xmx256m -Xmn128m -XX:MetaspaceSize=128m  -XX:MaxMetaspaceSize=320m"
    command: sh mqnamesrv -c /home/rocketmq/conf/nameserv.conf
    restart: always
    network_mode: host

  namesev-1:
    image: apache/rocketmq:5.3.1
    container_name: namesev-1
    privileged: true
    volumes:
      - /home/rocketmq/dledger/logs/node2:/opt/logs/rocketmqlogs
      - /home/rocketmq/dledger/node1/conf/nameserv1.propterties:/home/rocketmq/conf/nameserv.conf
    environment:
      ROCKETMQ_NAMESRV_PORT: 9877
      JAVA_OPT_EXT: "-Duser.home=/opt -Xms256m -Xmx256m -Xmn128m -XX:MetaspaceSize=128m  -XX:MaxMetaspaceSize=320m"
    command: sh mqnamesrv -c /home/rocketmq/conf/nameserv.conf
    restart: always
    network_mode: host

  namesev-2:
    image: apache/rocketmq:5.3.1
    container_name: namesev-2
    privileged: true
    volumes:
      - /home/rocketmq/dledger/logs/node3:/opt/logs/rocketmqlogs
      - /home/rocketmq/dledger/node2/conf/nameserv2.propterties:/home/rocketmq/conf/nameserv.conf
    environment:
      ROCKETMQ_NAMESRV_PORT: 9878
      JAVA_OPT_EXT: "-Duser.home=/opt -Xms256m -Xmx256m -Xmn128m -XX:MetaspaceSize=128m  -XX:MaxMetaspaceSize=320m"
    command: sh mqnamesrv -c /home/rocketmq/conf/nameserv.conf
    restart: always
    network_mode: host

  broker0:
    image: apache/rocketmq:5.3.1
    container_name: broker0
    privileged: true
    command: sh mqbroker -c /home/rocketmq/conf/broker.conf
    depends_on:
      - namesev-0
      - namesev-1
      - namesev-2
    volumes:
      - /home/rocketmq/dledger/node0/conf/node0.conf:/home/rocketmq/conf/broker.conf
    #      - /home/rocketmq/dledger/node0/logs/:/home/rocketmq/logs
    #      - /home/rocketmq/dledger/node0/store/:/home/rocketmq/store
    environment:
      <<: *base
    restart: always
    network_mode: host

  broker1:
    image: apache/rocketmq:5.3.1
    container_name: broker1
    privileged: true
    command: sh mqbroker -c /home/rocketmq/conf/broker.conf
    depends_on:
      - namesev-0
      - namesev-1
      - namesev-2
    volumes:
      - /home/rocketmq/dledger/node1/conf/node1.conf:/home/rocketmq/conf/broker.conf
    #      - /home/rocketmq/dledger/node1/logs/:/home/rocketmq/logs
    #      - /home/rocketmq/dledger/node1/store/:/home/rocketmq/store
    environment:
      <<: *base
    restart: always
    network_mode: host

  broker2:
    image: apache/rocketmq:5.3.1
    container_name: broker2
    privileged: true
    command: sh mqbroker -c /home/rocketmq/conf/broker.conf
    depends_on:
      - namesev-0
      - namesev-1
      - namesev-2
    volumes:
      - /home/rocketmq/dledger/node2/conf/node2.conf:/home/rocketmq/conf/broker.conf
    #      - /home/rocketmq/dledger/node1/logs/:/home/rocketmq/logs
    #      - /home/rocketmq/dledger/node1/store/:/home/rocketmq/store
    environment:
      <<: *base
    restart: always
    network_mode: host

  proxy:
    image: apache/rocketmq:5.3.1
    container_name: rmqproxy
    privileged: true
    network_mode: host
    depends_on:
      - namesev-0
      - namesev-1
      - namesev-2
      - broker0
      - broker1
      - broker2
    volumes:
      - /home/rocketmq/dledger/rmq-proxy.json:/home/rocketmq/rocketmq-5.3.1/conf/rmq-proxy.json
    restart: on-failure
    environment:
      NAMESRV_ADDR: "10.10.0.169:9876;10.10.0.169:9877;10.10.0.169:9878"
      JAVA_OPT_EXT: "-server -Xms256m -Xmx1024m -Xmn128m -XX:MetaspaceSize=128m  -XX:MaxMetaspaceSize=320m"
      JAVA_OPTS: "-Duser.home=/opt"
    command: sh mqproxy -pc /home/rocketmq/rocketmq-5.3.1/conf/rmq-proxy.json -pm cluster