server:
  port: 8900


rocketmq:
  name-server: 10.10.0.169:9876;10.10.0.169:9877;10.10.0.169:9878
  producer:
    group: xcodev-group-producer
    send-message-timeout: 3000
    retry-times-when-send-async-failed: 2
  consumer:
    group: xcodev-group-consumer

